server.port: 8080
spring.thymeleaf.cache: false

---
spring:
  profiles: develop
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://smartphone-experimentation.eu:3306/androidExperimentation
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validationQuery: SELECT 1

---
spring:
  profiles: production
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/androidExperimentation
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validationQuery: SELECT 1

---
spring:
  profiles: test
