# port of the server
server.port: 8080
# caching of html templates
spring.thymeleaf.cache: false

# embedded server response compression
server.compression:
  enabled: true
  mime-types: application/json,text/html,text/plain

orion:
  url: "http://localhost:1026/"
  token: ""
  service: "smartphone"
  servicePath: "/"
